---
kind: pipeline
type: docker
name: fs_neo_org

platform:
  os: linux
  arch: amd64

steps:
  - name: make prod tarball
    image: registry.nspcc.ru/docker-local/ui_builder:latest
    environment:
      API_KEY:
        from_secret: sami_api_key
    commands:
      - git fetch --tags
      - export PKGNAME=`make pkgname`
      - make build
      - curl -H "X-JFrog-Art-Api:$API_KEY" -T "$PKGNAME" "https://registry.nspcc.ru/artifactory/fs.neo.org/$PKGNAME"
  - name: make test tarball
    image: registry.nspcc.ru/docker-local/ui_builder:latest
    environment:
      API_KEY:
        from_secret: sami_api_key
      BUILD_FLAG: "--prod --configuration=test"
    commands:
      - git fetch --tags
      - export SUFFIX='-test'
      - export PKGNAME=`make pkgname`
      - make build
      - curl -H "X-JFrog-Art-Api:$API_KEY" -T "$PKGNAME" "https://registry.nspcc.ru/artifactory/fs.neo.org/$PKGNAME"

trigger:
  event:
    - push
  branch:
    - master

image_pull_secrets:
- docker_auth
