---
kind: pipeline
type: docker
name: fs_neo_org

platform:
  os: linux
  arch: amd64

steps:
  - name: make prod tarball
    image: registry.nspcc.ru/docker-local/ui_builder:latest
    environment:
      API_KEY:
        from_secret: sami_api_key
    commands:
      - git fetch --tags
      - make languages
      - make build
      - export PKGNAME=`make pkgname`
      - export SHA1SUM=`shasum -a 1 $PKGNAME | awk '{ print $1 }'`
      - export MD5SUM=`md5sum $PKGNAME | awk '{ print $1 }'`
      - curl -H "X-JFrog-Art-Api:$$API_KEY" -H "X-Checksum-MD5:$$MD5SUM" -H "X-Checksum-Sha1:$$SHA1SUM" -T "$$PKGNAME" "https://registry.nspcc.ru/artifactory/fs.neo.org/$PKGNAME"
  - name: make localtest tarball
    image: registry.nspcc.ru/docker-local/ui_builder:latest
    environment:
      API_KEY:
        from_secret: sami_api_key
      BUILD_FLAG: "--prod --configuration=localtest"
    commands:
      - git fetch --tags
      - export SUFFIX='-localtest'
      - make languages
      - make build
      - export PKGNAME=`make pkgname`
      - export SHA1SUM=`shasum -a 1 $PKGNAME | awk '{ print $1 }'`
      - export MD5SUM=`md5sum $PKGNAME | awk '{ print $1 }'`
      - curl -H "X-JFrog-Art-Api:$$API_KEY" -H "X-Checksum-MD5:$$MD5SUM" -H "X-Checksum-Sha1:$$SHA1SUM" -T "$$PKGNAME" "https://registry.nspcc.ru/artifactory/fs.neo.org/$PKGNAME"

trigger:
  event:
    - push
    - tag
  branch:
    - master

image_pull_secrets:
- docker_auth
